class Solution {
        public int minSumOfLengths(int[] arr, int target) {
                int n = arr.length;
                        // best[i] will store the minimum length of a valid subarray ending at or before index i
                                int[] best = new int[n]; 
                                        int minLen = Integer.MAX_VALUE;
                                                int ans = Integer.MAX_VALUE;
                                                        
                                                                int left = 0;
                                                                        int sum = 0;
                                                                                
                                                                                        // Sliding window to find all subarrays that sum to the target
                                                                                                for (int right = 0; right < n; right++) {
                                                                                                            sum += arr[right];
                                                                                                                        
                                                                                                                                    // Shrink window if the sum exceeds the target
                                                                                                                                                while (sum > target && left <= right) {
                                                                                                                                                                sum -= arr[left];
                                                                                                                                                                                left++;
                                                                                                                                                                                            }
                                                                                                                                                                                                        
                                                                                                                                                                                                                    if (sum == target) {
                                                                                                                                                                                                                                    int currentLen = right - left + 1;
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                    // If there's a valid non-overlapping subarray before 'left', we can form a pair
                                                                                                                                                                                                                                                                                    if (left > 0 && best[left - 1] != Integer.MAX_VALUE) {
                                                                                                                                                                                                                                                                                                        ans = Math.min(ans, currentLen + best[left - 1]);
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        // Update the minimum length found so far
                                                                                                                                                                                                                                                                                                                                                                        minLen = Math.min(minLen, currentLen);
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                            // Store the best minimum length up to the current index 'right'
                                                                                                                                                                                                                                                                                                                                                                                                                        best[right] = minLen;
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                return ans == Integer.MAX_VALUE ? -1 : ans;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
