class Solution {
        private int[] treeProd;
            private int[][] treeFreq;
                private int K;

                    // Build the segment tree
                        private void build(int node, int start, int end, int[] nums) {
                                if (start == end) {
                                            int val = nums[start] % K;
                                                        treeProd[node] = val;
                                                                    treeFreq[node][val] = 1;
                                                                                return;
                                                                                        }
                                                                                                int mid = start + (end - start) / 2;
                                                                                                        build(2 * node, start, mid, nums);
                                                                                                                build(2 * node + 1, mid + 1, end, nums);
                                                                                                                        merge(node, 2 * node, 2 * node + 1);
                                                                                                                            }

                                                                                                                                // Merge left and right child data into the parent node
                                                                                                                                    private void merge(int node, int left, int right) {
                                                                                                                                            treeProd[node] = (treeProd[left] * treeProd[right]) % K;
                                                                                                                                                    
                                                                                                                                                            // Start with prefix frequencies from the left child
                                                                                                                                                                    for (int i = 0; i < K; i++) {
                                                                                                                                                                                treeFreq[node][i] = treeFreq[left][i];
                                                                                                                                                                                        }
                                                                                                                                                                                                
                                                                                                                                                                                                        // Add prefix frequencies extending into the right child
                                                                                                                                                                                                                int leftProd = treeProd[left];
                                                                                                                                                                                                                        for (int i = 0; i < K; i++) {
                                                                                                                                                                                                                                    if (treeFreq[right][i] > 0) {
                                                                                                                                                                                                                                                    treeFreq[node][(leftProd * i) % K] += treeFreq[right][i];
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                // Point update at 'idx' with new 'val'
                                                                                                                                                                                                                                                                                    private void update(int node, int start, int end, int idx, int val) {
                                                                                                                                                                                                                                                                                            if (start == end) {
                                                                                                                                                                                                                                                                                                        int modVal = val % K;
                                                                                                                                                                                                                                                                                                                    treeProd[node] = modVal;
                                                                                                                                                                                                                                                                                                                                for (int i = 0; i < K; i++) treeFreq[node][i] = 0;
                                                                                                                                                                                                                                                                                                                                            treeFreq[node][modVal] = 1;
                                                                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                        int mid = start + (end - start) / 2;
                                                                                                                                                                                                                                                                                                                                                                                if (idx <= mid) {
                                                                                                                                                                                                                                                                                                                                                                                            update(2 * node, start, mid, idx, val);
                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                update(2 * node + 1, mid + 1, end, idx, val);
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                merge(node, 2 * node, 2 * node + 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                        // Range query returning an array where [0..K-1] are frequencies and [K] is the total range product
                                                                                                                                                                                                                                                                                                                                                                                                                                            private int[] query(int node, int start, int end, int l, int r) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (l <= start && end <= r) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                int[] res = new int[K + 1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int i = 0; i < K; i++) res[i] = treeFreq[node][i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res[K] = treeProd[node];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int mid = start + (end - start) / 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (r <= mid) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return query(2 * node, start, mid, l, r);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else if (l > mid) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return query(2 * node + 1, mid + 1, end, l, r);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int[] leftRes = query(2 * node, start, mid, l, mid);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int[] rightRes = query(2 * node + 1, mid + 1, end, mid + 1, r);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int[] res = new int[K + 1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res[K] = (leftRes[K] * rightRes[K]) % K;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int i = 0; i < K; i++) res[i] = leftRes[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int lProd = leftRes[K];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int i = 0; i < K; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (rightRes[i] > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res[(lProd * i) % K] += rightRes[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return res;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public int[] resultArray(int[] nums, int k, int[][] queries) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    this.K = k;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int n = nums.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    treeProd = new int[4 * n + 1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            treeFreq = new int[4 * n + 1][k];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            build(1, 0, n - 1, nums);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int[] ans = new int[queries.length];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int i = 0; i < queries.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int index = queries[i][0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int value = queries[i][1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int start = queries[i][2];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int x = queries[i][3];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // 1. Update the value at 'index'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    update(1, 0, n - 1, index, value);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 2. Query the frequencies for the range [start, n - 1]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int[] res = query(1, 0, n - 1, start, n - 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 3. Store the result for remainder 'x'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ans[i] = res[x];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return ans;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
