class Solution {
        public int minInsertions(String s) {
                int insertions = 0;
                        int rightNeeded = 0;
                                
                                        for (int i = 0; i < s.length(); i++) {
                                                    char c = s.charAt(i);
                                                                
                                                                            if (c == '(') {
                                                                                            // If we have an odd number of right parentheses needed (e.g., 1),
                                                                                                            // we must insert one ')' to complete the previous '))' group 
                                                                                                                            // before opening a new '('.
                                                                                                                                            if (rightNeeded % 2 != 0) {
                                                                                                                                                                insertions++;
                                                                                                                                                                                    rightNeeded--;
                                                                                                                                                                                                    }
                                                                                                                                                                                                                    // Each '(' requires two ')'
                                                                                                                                                                                                                                    rightNeeded += 2;
                                                                                                                                                                                                                                                } else { // c == ')'
                                                                                                                                                                                                                                                                rightNeeded--;
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                // If rightNeeded becomes negative, it means we have a ')' 
                                                                                                                                                                                                                                                                                                                // without a preceding '('. We must insert a '('.
                                                                                                                                                                                                                                                                                                                                if (rightNeeded < 0) {
                                                                                                                                                                                                                                                                                                                                                    insertions++; // Insert one '('
                                                                                                                                                                                                                                                                                                                                                                        // A newly inserted '(' needs two ')'. Since we just processed one ')', 
                                                                                                                                                                                                                                                                                                                                                                                            // we still need exactly one more ')'.
                                                                                                                                                                                                                                                                                                                                                                                                                rightNeeded = 1; 
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Add any remaining required ')' to the total insertions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return insertions + rightNeeded;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
