class Solution {
        public List<String> maxNumOfSubstrings(String s) {
                int[] L = new int[26];
                        int[] R = new int[26];
                                Arrays.fill(L, -1);
                                        Arrays.fill(R, -1);
                                                
                                                        int n = s.length();
                                                                // Step 1: Find the first and last occurrence of each character.
                                                                        for (int i = 0; i < n; i++) {
                                                                                    int c = s.charAt(i) - 'a';
                                                                                                if (L[c] == -1) {
                                                                                                                L[c] = i;
                                                                                                                            }
                                                                                                                                        R[c] = i;
                                                                                                                                                }
                                                                                                                                                        
                                                                                                                                                                List<int[]> intervals = new ArrayList<>();
                                                                                                                                                                        // Step 2: Try to form a valid substring starting from the first occurrence of each character.
                                                                                                                                                                                for (int i = 0; i < 26; i++) {
                                                                                                                                                                                            if (L[i] != -1) {
                                                                                                                                                                                                            int right = getRight(L[i], L, R, s);
                                                                                                                                                                                                                            if (right != -1) {
                                                                                                                                                                                                                                                intervals.add(new int[]{L[i], right});
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                    // Step 3: Greedily pick the maximum number of non-overlapping substrings.
                                                                                                                                                                                                                                                                                                            // Sort by end time ascending. If tied, sort by start time descending to prefer shorter length.
                                                                                                                                                                                                                                                                                                                    Collections.sort(intervals, (a, b) -> a[1] == b[1] ? b[0] - a[0] : a[1] - b[1]);
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                    List<String> res = new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                            int lastEnd = -1;
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                            for (int[] interval : intervals) {
                                                                                                                                                                                                                                                                                                                                                                        if (interval[0] > lastEnd) {
                                                                                                                                                                                                                                                                                                                                                                                        res.add(s.substring(interval[0], interval[1] + 1));
                                                                                                                                                                                                                                                                                                                                                                                                        lastEnd = interval[1];
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                            return res;
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Validates and returns the rightmost boundary for a substring starting at index 'i'.
                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Returns -1 if a valid substring cannot be formed starting exactly at 'i'.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                private int getRight(int i, int[] L, int[] R, String s) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int right = R[s.charAt(i) - 'a'];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int j = i; j <= right; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // If a character inside our window appears before our starting point 'i',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // this starting point is invalid. We will handle it when we process the earlier character.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (L[s.charAt(j) - 'a'] < i) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return -1; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Expand the right boundary if a character appears later in the string.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        right = Math.max(right, R[s.charAt(j) - 'a']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return right;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
