class Solution {
        public boolean hasValidPath(char[][] grid) {
                int m = grid.length;
                        int n = grid[0].length;
                                
                                        // A valid parentheses string must have an even length.
                                                // The length of any path from (0,0) to (m-1, n-1) is m + n - 1.
                                                        if ((m + n - 1) % 2 != 0) {
                                                                    return false;
                                                                            }
                                                                                    
                                                                                            // A valid string cannot start with a closing bracket or end with an opening bracket.
                                                                                                    if (grid[0][0] == ')' || grid[m - 1][n - 1] == '(') {
                                                                                                                return false;
                                                                                                                        }
                                                                                                                                
                                                                                                                                        // visited[row][col][balance] to memoize the states we have already computed
                                                                                                                                                // The maximum possible balance is bounded by the maximum path length divided by 2
                                                                                                                                                        boolean[][][] visited = new boolean[m][n][(m + n) / 2 + 1];
                                                                                                                                                                
                                                                                                                                                                        return dfs(grid, 0, 0, 0, visited);
                                                                                                                                                                            }
                                                                                                                                                                                
                                                                                                                                                                                    private boolean dfs(char[][] grid, int r, int c, int balance, boolean[][][] visited) {
                                                                                                                                                                                            int m = grid.length;
                                                                                                                                                                                                    int n = grid[0].length;
                                                                                                                                                                                                            
                                                                                                                                                                                                                    // Update the balance based on the current cell
                                                                                                                                                                                                                            if (grid[r][c] == '(') {
                                                                                                                                                                                                                                        balance++;
                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                            balance--;
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                    // If balance drops below 0, there are more closing brackets than opening ones (invalid)
                                                                                                                                                                                                                                                                                            // If balance exceeds (m + n) / 2, it's impossible to close all the opening brackets by the end
                                                                                                                                                                                                                                                                                                    if (balance < 0 || balance > (m + n) / 2) {
                                                                                                                                                                                                                                                                                                                return false;
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                        // If we reached the bottom-right corner, check if the string is perfectly balanced
                                                                                                                                                                                                                                                                                                                                                if (r == m - 1 && c == n - 1) {
                                                                                                                                                                                                                                                                                                                                                            return balance == 0;
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                    // If this state has been visited before and didn't lead to a valid path, prune it
                                                                                                                                                                                                                                                                                                                                                                                            if (visited[r][c][balance]) {
                                                                                                                                                                                                                                                                                                                                                                                                        return false;
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                // Mark the current state as visited
                                                                                                                                                                                                                                                                                                                                                                                                                                        visited[r][c][balance] = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Try moving down (r + 1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (r + 1 < m && dfs(grid, r + 1, c, balance, visited)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Try moving right (c + 1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (c + 1 < n && dfs(grid, r, c + 1, balance, visited)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
