class Solution {
        public long minSumSquareDiff(int[] nums1, int[] nums2, int k1, int k2) {
                int n = nums1.length;
                        long[] counts = new long[100001];
                                long sum = 0;
                                        long k = (long) k1 + k2; // Combine total operations
                                                
                                                        int maxDiff = 0;
                                                                
                                                                        // Calculate absolute differences and populate the frequency array
                                                                                for (int i = 0; i < n; i++) {
                                                                                            int diff = Math.abs(nums1[i] - nums2[i]);
                                                                                                        counts[diff]++;
                                                                                                                    sum += diff;
                                                                                                                                maxDiff = Math.max(maxDiff, diff);
                                                                                                                                        }
                                                                                                                                                
                                                                                                                                                        // If we have enough operations to reduce all differences to 0
                                                                                                                                                                if (sum <= k) {
                                                                                                                                                                            return 0;
                                                                                                                                                                                    }
                                                                                                                                                                                            
                                                                                                                                                                                                    // Greedily reduce the largest differences first
                                                                                                                                                                                                            for (int i = maxDiff; i > 0 && k > 0; i--) {
                                                                                                                                                                                                                        if (counts[i] > 0) {
                                                                                                                                                                                                                                        // Determine how many items of current difference 'i' we can reduce
                                                                                                                                                                                                                                                        long take = Math.min(counts[i], k);
                                                                                                                                                                                                                                                                        counts[i] -= take;
                                                                                                                                                                                                                                                                                        counts[i - 1] += take;
                                                                                                                                                                                                                                                                                                        k -= take;
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                            // Calculate the final minimum sum of squared differences
                                                                                                                                                                                                                                                                                                                                                    long ans = 0;
                                                                                                                                                                                                                                                                                                                                                            for (int i = 1; i <= maxDiff; i++) {
                                                                                                                                                                                                                                                                                                                                                                        if (counts[i] > 0) {
                                                                                                                                                                                                                                                                                                                                                                                        ans += counts[i] * (long) i * i;
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                            return ans;
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                
}