class Solution {
        public long[] resultArray(int[] nums, int k) {
                long[] res = new long[k];
                        long[] dp = new long[k];
                                long[] nextDp = new long[k];

                                        // Track active remainders to prevent O(N * K) TLE if K is large
                                                int[] active = new int[k];
                                                        boolean[] inActive = new boolean[k];
                                                                int activeCount = 0;

                                                                        int[] nextActive = new int[k];
                                                                                boolean[] nextInActive = new boolean[k];

                                                                                        for (int num : nums) {
                                                                                                    int nextCount = 0;
                                                                                                                int rem = num % k;

                                                                                                                            // 1. Start a new subarray at the current element
                                                                                                                                        nextDp[rem] = 1;
                                                                                                                                                    nextActive[nextCount++] = rem;
                                                                                                                                                                nextInActive[rem] = true;

                                                                                                                                                                            // 2. Extend existing subarrays ending at the previous index
                                                                                                                                                                                        for (int i = 0; i < activeCount; i++) {
                                                                                                                                                                                                        int r = active[i];
                                                                                                                                                                                                                        int nextRem = (int) (((long) r * rem) % k);
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                        nextDp[nextRem] += dp[r];
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                        if (!nextInActive[nextRem]) {
                                                                                                                                                                                                                                                                                                            nextInActive[nextRem] = true;
                                                                                                                                                                                                                                                                                                                                nextActive[nextCount++] = nextRem;
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                        // 3. Clear previous states
                                                                                                                                                                                                                                                                                                                                                                                    for (int i = 0; i < activeCount; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                    dp[active[i]] = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                    inActive[active[i]] = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                            // 4. Accumulate to result and transfer next states to current
                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int i = 0; i < nextCount; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int r = nextActive[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res[r] += nextDp[r];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dp[r] = nextDp[r];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        active[i] = r;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        inActive[r] = true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Clear for the next iteration
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        nextDp[r] = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        nextInActive[r] = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                activeCount = nextCount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return res;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
